### ISSUE TITLE
Downloading some host URLs will throw a 403 error

### ISSUE THREAD

**Issue by ndfred** [ndfred/unifi-pi-hole#1]
Uncomment the `ads_lists = download_ads_list_urls('https://v.firebog.net/hosts/lists.php?type=tick')` line in `build_rules.py` and boom:

	$ ./build_rules.py 
	Parsing https://hosts-file.net/grm.txt
	Parsing https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
	Parsing https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
	Parsing https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
	Parsing https://v.firebog.net/hosts/static/w3kbl.txt
	Parsing https://adaway.org/hosts.txt
	Traceback (most recent call last):
	  File "./build_rules.py", line 99, in <module>
	    sys.exit(main())
	  File "./build_rules.py", line 94, in main
	    output_rules('configure.sh')
	  File "./build_rules.py", line 74, in output_rules
	    for domain in parse_host_file(url):
	  File "./build_rules.py", line 59, in parse_host_file
	    for line in download_file(url).split('\n'):
	  File "./build_rules.py", line 25, in download_file
	    return urllib2.urlopen(url).read()
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
	    return opener.open(url, data, timeout)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
	    response = meth(req, response)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
	    'http', request, response, code, msg, hdrs)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
	    return self._call_chain(*args)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
	    result = func(*args)
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
	    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
	urllib2.HTTPError: HTTP Error 403: Forbidden

This doesn't occur when using `curl` so something in the python fetching stack is not behaving right.

**Comment by ndfred** [comment]
`curl` debug mode:

	$ curl -v -L https://adaway.org/hosts.txt
	*   Trying 104.24.104.89...
	* TCP_NODELAY set
	* Connected to adaway.org (104.24.104.89) port 443 (#0)
	* ALPN, offering h2
	* ALPN, offering http/1.1
	* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
	* successfully set certificate verify locations:
	*   CAfile: /etc/ssl/cert.pem
	  CApath: none
	* TLSv1.2 (OUT), TLS handshake, Client hello (1):
	* TLSv1.2 (IN), TLS handshake, Server hello (2):
	* TLSv1.2 (IN), TLS handshake, Certificate (11):
	* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
	* TLSv1.2 (IN), TLS handshake, Server finished (14):
	* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
	* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
	* TLSv1.2 (OUT), TLS handshake, Finished (20):
	* TLSv1.2 (IN), TLS change cipher, Client hello (1):
	* TLSv1.2 (IN), TLS handshake, Finished (20):
	* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
	* ALPN, server accepted to use h2
	* Server certificate:
	*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni65741.cloudflaressl.com
	*  start date: Mar  8 00:00:00 2019 GMT
	*  expire date: Sep 14 23:59:59 2019 GMT
	*  subjectAltName: host "adaway.org" matched cert's "adaway.org"
	*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
	*  SSL certificate verify ok.
	* Using HTTP2, server supports multi-use
	* Connection state changed (HTTP/2 confirmed)
	* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
	* Using Stream ID: 1 (easy handle 0x7fca57800400)
	> GET /hosts.txt HTTP/2
	> Host: adaway.org
	> User-Agent: curl/7.54.0
	> Accept: */*
	> 
	* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
	< HTTP/2 200 
	< date: Sat, 27 Apr 2019 09:10:17 GMT
	< content-type: text/plain; charset=utf-8
	< set-cookie: __cfduid=d97264f8e2f00098234528dc395aef4de1556356217; expires=Sun, 26-Apr-20 09:10:17 GMT; path=/; domain=.adaway.org; HttpOnly
	< last-modified: Sat, 20 Jan 2018 18:32:43 GMT
	< etag: W/"5a638b4b-359a"
	< access-control-allow-origin: *
	< expires: Wed, 10 Apr 2019 01:44:20 GMT
	< cache-control: max-age=600
	< x-github-request-id: AEEA:148F:2D5D31:3BA451:5CAD4982
	< via: 1.1 varnish
	< age: 308
	< x-served-by: cache-lcy19243-LCY
	< x-cache: HIT
	< x-cache-hits: 3
	< x-timer: S1556356218.669444,VS0,VE0
	< vary: Accept-Encoding
	< x-fastly-request-id: e93c13deac68932a4acd635a938299e1c38f19e6
	< strict-transport-security: max-age=0
	< x-content-type-options: nosniff
	< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
	< server: cloudflare
	< cf-ray: 4cdfa9986c6dce71-LHR
	< 
	# AdAway default blocklist
	# Blocking mobile ad providers and some analytics providers
	[...]

This might be due to HTTP/2 or the user agent being different.

**Comment by ndfred** [comment]
Forcing HTTP 1.1 doesn't improve things, odd we are seeing this behavior when querying Cloudflare:

	$ curl -v -L --http1.1 https://adaway.org/hosts.txt
	*   Trying 104.24.104.89...
	* TCP_NODELAY set
	* Connected to adaway.org (104.24.104.89) port 443 (#0)
	* ALPN, offering http/1.1
	* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
	* successfully set certificate verify locations:
	*   CAfile: /etc/ssl/cert.pem
	  CApath: none
	* TLSv1.2 (OUT), TLS handshake, Client hello (1):
	* TLSv1.2 (IN), TLS handshake, Server hello (2):
	* TLSv1.2 (IN), TLS handshake, Certificate (11):
	* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
	* TLSv1.2 (IN), TLS handshake, Server finished (14):
	* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
	* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
	* TLSv1.2 (OUT), TLS handshake, Finished (20):
	* TLSv1.2 (IN), TLS change cipher, Client hello (1):
	* TLSv1.2 (IN), TLS handshake, Finished (20):
	* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
	* ALPN, server accepted to use http/1.1
	* Server certificate:
	*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=sni65741.cloudflaressl.com
	*  start date: Mar  8 00:00:00 2019 GMT
	*  expire date: Sep 14 23:59:59 2019 GMT
	*  subjectAltName: host "adaway.org" matched cert's "adaway.org"
	*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
	*  SSL certificate verify ok.
	> GET /hosts.txt HTTP/1.1
	> Host: adaway.org
	> User-Agent: curl/7.54.0
	> Accept: */*
	> 
	< HTTP/1.1 200 OK
	< Date: Sat, 27 Apr 2019 09:13:32 GMT
	< Content-Type: text/plain; charset=utf-8
	< Transfer-Encoding: chunked
	< Connection: keep-alive
	< Set-Cookie: __cfduid=d8af72643189ba0efcd9aae608dd03c351556356412; expires=Sun, 26-Apr-20 09:13:32 GMT; path=/; domain=.adaway.org; HttpOnly
	< Last-Modified: Sat, 20 Jan 2018 18:32:43 GMT
	< ETag: W/"5a638b4b-359a"
	< Access-Control-Allow-Origin: *
	< Expires: Wed, 10 Apr 2019 01:44:20 GMT
	< Cache-Control: max-age=600
	< X-GitHub-Request-Id: AEEA:148F:2D5D31:3BA451:5CAD4982
	< Via: 1.1 varnish
	< Age: 504
	< X-Served-By: cache-lcy19224-LCY
	< X-Cache: HIT
	< X-Cache-Hits: 4
	< X-Timer: S1556356413.957446,VS0,VE0
	< Vary: Accept-Encoding
	< X-Fastly-Request-ID: eb84b4fb1f8795c08b4a95dc07db316d29aac4db
	< Strict-Transport-Security: max-age=0
	< X-Content-Type-Options: nosniff
	< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
	< Server: cloudflare
	< CF-RAY: 4cdfae5cec9135cc-LHR
	< 
	# AdAway default blocklist
	# Blocking mobile ad providers and some analytics providers
